// This script generates the full HTML - run with: node build.js > index.html

console.log(`<!DOCTYPE html>
<html lang="de">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Mission Control</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet">
<style>*{margin:0;padding:0;box-sizing:border-box}:root{--bg:#0a0a0f;--glass:rgba(255,255,255,.05);--border:rgba(255,255,255,.07);--text:#e2e2e8;--dim:#7779a0;--cyan:#06b6d4;--emerald:#10b981;--purple:#8b5cf6;--amber:#f59e0b;--red:#ef4444;--blue:#3b82f6}html{scroll-behavior:smooth}body{font-family:'Inter',sans-serif;background:var(--bg);color:var(--text);min-height:100vh;overflow-x:hidden;line-height:1.5;font-size:14px}.bg{position:fixed;inset:0;z-index:0;pointer-events:none;background-image:linear-gradient(rgba(6,182,212,.02) 1px,transparent 1px),linear-gradient(90deg,rgba(6,182,212,.02) 1px,transparent 1px);background-size:60px 60px}.app{display:flex;min-height:100vh;position:relative;z-index:1}.sidebar{width:256px;background:rgba(10,10,15,.96);border-right:1px solid var(--border);display:flex;flex-direction:column;position:fixed;left:0;top:0;bottom:0;overflow-y:auto;z-index:100}.sb-brand{height:60px;display:flex;align-items:center;gap:10px;padding:0 16px;border-bottom:1px solid var(--border);flex-shrink:0}.sb-logo{width:28px;height:28px;border-radius:8px;background:linear-gradient(135deg,var(--purple),var(--cyan));display:flex;align-items:center;justify-content:center;font-size:11px;font-weight:900;color:#fff}.sb-title{font-size:.75rem;font-weight:700;text-transform:uppercase;letter-spacing:.06em;color:#999}
.sb-nav{flex:1;padding:8px}.sb-sec{font-size:.6rem;font-weight:700;text-transform:uppercase;color:var(--dim);padding:10px 10px 4px}.nav-item{display:flex;align-items:center;gap:10px;padding:8px 10px;border-radius:8px;cursor:pointer;color:var(--dim);font-size:.82rem;margin-bottom:2px;border:1px solid transparent;transition:all .2s}.nav-item:hover{background:var(--glass);color:var(--text)}.nav-item.active{background:rgba(255,255,255,.08);color:var(--text);border-color:var(--cyan)}.nav-icon{font-size:.9rem;width:18px;text-align:center}.nav-badge{margin-left:auto;background:var(--cyan);color:#000;font-size:.6rem;font-weight:700;padding:1px 5px;border-radius:999px;min-width:16px;text-align:center}
.sb-footer{padding:10px;border-top:1px solid var(--border);flex-shrink:0}.sb-user{display:flex;gap:8px}.sb-av{width:30px;height:30px;border-radius:8px;background:linear-gradient(135deg,var(--purple),var(--cyan));display:flex;align-items:center;justify-content:center;font-size:13px}.sb-uname{font-size:.8rem;font-weight:600;color:#fff}.sb-status{font-size:.65rem;color:var(--emerald);display:flex;align-items:center;gap:3px}.sb-status::before{content:'';width:5px;height:5px;border-radius:50%;background:var(--emerald);animation:pulse 2s infinite}
@keyframes pulse{0%,100%{opacity:1;transform:scale(1)}50%{opacity:.5;transform:scale(.8)}}@keyframes fade{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}}.main{margin-left:256px;flex:1;display:flex;flex-direction:column;min-height:100vh}.header{height:60px;background:rgba(10,10,15,.9);border-bottom:1px solid var(--border);display:flex;align-items:center;padding:0 20px;gap:10px;position:sticky;top:0;z-index:50;flex-shrink:0}.hdr-page{font-size:.9rem;font-weight:700;color:var(--text)}.hdr-sp{flex:1}.hdr-clock{font-size:.75rem;color:var(--dim);font-variant-numeric:tabular-nums;background:var(--glass);border:1px solid var(--border);padding:4px 11px;border-radius:999px}
.pages{flex:1;overflow-y:auto}.page{display:none;padding:20px;animation:fade .25s ease}.page.active{display:block}.gc{background:var(--glass);border:1px solid var(--border);border-radius:12px;transition:all .2s;overflow:hidden}.gc:hover{border-color:rgba(6,182,212,.3)}.sec-title{font-size:.95rem;font-weight:700;margin-bottom:12px;display:flex;gap:8px;align-items:center}.sec-title .sub{font-size:.7rem;color:var(--dim);font-weight:400}.badge{display:inline-flex;align-items:center;gap:3px;font-size:.6rem;font-weight:600;padding:2px 6px;border-radius:999px;text-transform:uppercase;border:1px solid}.bc{color:var(--cyan);background:rgba(6,182,212,.12);border-color:rgba(6,182,212,.25)}.be{color:var(--emerald);background:rgba(16,185,129,.12);border-color:rgba(16,185,129,.25)}.br{color:var(--red);background:rgba(239,68,68,.12);border-color:rgba(239,68,68,.25)}
.dash-kpi{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:18px}.kpi{padding:16px;position:relative}.kpi-icon{font-size:1.3rem;margin-bottom:6px}.kpi-val{font-size:1.8rem;font-weight:800;line-height:1;margin-bottom:3px}.kpi-label{font-size:.65rem;color:var(--dim);text-transform:uppercase}.kpi-bar{position:absolute;bottom:0;left:0;right:0;height:2px;opacity:.8}.kpi-c .kpi-val{color:var(--cyan)}.kpi-c .kpi-bar{background:linear-gradient(90deg,var(--cyan),transparent)}.kpi-e .kpi-val{color:var(--emerald)}.kpi-e .kpi-bar{background:linear-gradient(90deg,var(--emerald),transparent)}.kpi-a .kpi-val{color:var(--amber)}.kpi-a .kpi-bar{background:linear-gradient(90deg,var(--amber),transparent)}.kpi-p .kpi-val{color:var(--purple)}.kpi-p .kpi-bar{background:linear-gradient(90deg,var(--purple),transparent)}
.dash-lower{display:grid;grid-template-columns:1fr 280px;gap:14px}.activity{padding:14px;max-height:400px;overflow-y:auto}.act-item{display:flex;gap:8px;margin-bottom:7px;font-size:.76rem;border-bottom:1px solid rgba(255,255,255,.04);padding-bottom:7px}.act-item:last-child{border-bottom:none}.act-dot{width:6px;height:6px;border-radius:50%;margin-top:3px;flex-shrink:0}.act-txt{flex:1;line-height:1.5}.act-txt strong{color:#fff;font-weight:600}.act-time{font-size:.65rem;color:var(--dim);margin-top:2px}.aq{padding:12px;max-height:400px;overflow-y:auto}.ar{display:flex;align-items:center;gap:8px;padding:5px 0;border-bottom:1px solid rgba(255,255,255,.04);font-size:.76rem}.ar:last-child{border-bottom:none}.ar-icon{font-size:.9rem;width:22px;text-align:center}.ar-name{font-weight:600;flex:1}.ar-task{color:var(--dim);font-size:.7rem}.sd{width:6px;height:6px;border-radius:50%;flex-shrink:0}.on{background:var(--emerald);box-shadow:0 0 4px var(--emerald);animation:pulse 2s infinite}.sb{background:var(--amber)}.off{background:var(--dim)}
.tasks-top{display:flex;gap:10px;margin-bottom:10px;align-items:center}.btn{background:linear-gradient(135deg,var(--cyan),var(--purple));color:#fff;border:none;padding:7px 14px;border-radius:8px;font-size:.78rem;font-weight:600;cursor:pointer;transition:all .2s}.btn:hover{opacity:.85;transform:translateY(-1px)}.tstat{display:flex;gap:10px;margin-bottom:12px;flex-wrap:wrap}.ts{padding:10px 14px;background:var(--glass);border:1px solid var(--border);border-radius:8px;flex:1;min-width:80px;text-align:center}.ts-val{font-size:1.3rem;font-weight:800}.ts-label{font-size:.62rem;color:var(--dim);text-transform:uppercase;letter-spacing:.04em}
.kanban{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.kcol{background:var(--glass);border:1px solid var(--border);border-radius:12px;min-height:350px;display:flex;flex-direction:column}.kcol.dov{border-color:var(--cyan);background:rgba(6,182,212,.08)}.kcol-hd{padding:10px 12px;border-bottom:1px solid var(--border);display:flex;gap:6px;align-items:center}.kcol-dot{width:6px;height:6px;border-radius:50%;flex-shrink:0}.kcol-title{font-size:.7rem;font-weight:700;text-transform:uppercase;letter-spacing:.04em}.kcol-cnt{margin-left:auto;font-size:.62rem;background:rgba(255,255,255,.04);padding:1px 6px;border-radius:999px;color:var(--dim)}.kcol-body{padding:6px;flex:1;display:flex;flex-direction:column;gap:6px;overflow-y:auto}
.tcard{background:rgba(255,255,255,.035);border:1px solid var(--border);border-radius:8px;padding:9px 10px;cursor:grab;transition:all .2s;user-select:none}.tcard:hover{border-color:var(--cyan);transform:translateY(-2px);box-shadow:0 4px 12px rgba(0,0,0,.3)}.tcard.dragging{opacity:.25}.tc-title{font-size:.78rem;font-weight:600;margin-bottom:3px;color:#fff}.tc-desc{font-size:.69rem;color:var(--dim);margin-bottom:7px;line-height:1.5}.tc-foot{display:flex;gap:4px;flex-wrap:wrap;font-size:.62rem;align-items:center}.tc-asgn{background:rgba(255,255,255,.06);padding:2px 6px;border-radius:999px;color:var(--dim)}.prio{width:5px;height:5px;border-radius:50%;flex-shrink:0}.pc{background:var(--red);box-shadow:0 0 3px var(--red)}.ph{background:var(--amber)}.pm{background:var(--blue)}.pl{background:var(--dim)}
.pipeline{display:grid;grid-template-columns:repeat(5,1fr);gap:10px}.pcol{background:var(--glass);border:1px solid var(--border);border-radius:12px;min-height:300px;display:flex;flex-direction:column}.pcol-hd{padding:10px;border-bottom:1px solid var(--border);display:flex;gap:6px;font-size:.7rem;font-weight:700;text-transform:uppercase}.pcol-dot{width:5px;height:5px;border-radius:50%;flex-shrink:0}.pcol-body{padding:6px;flex:1;overflow-y:auto}.ccard{background:rgba(255,255,255,.04);border:1px solid var(--border);border-radius:8px;padding:8px 10px;margin-bottom:6px;cursor:pointer;transition:all .2s;font-size:.74rem}.ccard:hover{border-color:var(--cyan);transform:translateY(-2px)}.cc-title{font-weight:600;margin-bottom:2px;color:#fff}.cc-desc{color:var(--dim);font-size:.68rem;line-height:1.4}
.mem-srch{display:flex;gap:8px;background:var(--glass);border:1px solid var(--border);border-radius:8px;padding:7px 11px;margin-bottom:12px}.mem-srch input{flex:1;background:none;border:none;outline:none;color:var(--text);font-size:.8rem}.mem-srch input::placeholder{color:var(--dim)}.mem-filters{display:flex;gap:6px;margin-bottom:12px;flex-wrap:wrap}.filt{padding:5px 11px;border-radius:999px;background:var(--glass);border:1px solid var(--border);color:var(--dim);font-size:.7rem;font-weight:600;cursor:pointer;transition:all .2s}.filt:hover{border-color:var(--cyan);color:var(--text)}.filt.active{background:rgba(6,182,212,.12);border-color:var(--cyan);color:var(--cyan)}.mem-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(270px,1fr));gap:12px}.mcard{padding:12px 14px;border-left:3px solid;border-radius:8px;background:var(--glass);border:1px solid var(--border);transition:all .2s}.mcard:hover{transform:translateY(-2px)}.mcard-project{border-left-color:var(--cyan)}.mcard-personal{border-left-color:var(--emerald)}.mcard-lesson{border-left-color:var(--amber)}.mcard-creds{border-left-color:var(--purple)}.mc-cat{font-size:.59rem;font-weight:700;text-transform:uppercase;color:var(--dim);margin-bottom:4px;letter-spacing:.04em}.mc-title{font-size:.84rem;font-weight:700;margin-bottom:3px;color:#fff}.mc-preview{font-size:.73rem;color:var(--dim);line-height:1.5;margin-bottom:6px}.mc-date{font-size:.63rem;color:var(--dim)}
.cal-nav{display:flex;gap:10px;margin-bottom:10px}.cal-btn{background:var(--glass);border:1px solid var(--border);color:var(--text);padding:6px 10px;border-radius:8px;cursor:pointer;font-size:.75rem;transition:all .2s}.cal-btn:hover{border-color:var(--cyan)}.cal-legend{display:flex;gap:10px;margin-bottom:10px;flex-wrap:wrap;font-size:.68rem}.cal-li{display:flex;gap:4px;align-items:center}.cal-ldot{width:6px;height:6px;border-radius:50%}.cal{border:1px solid var(--border);border-radius:12px;background:var(--glass);overflow:hidden}.cal-hrow{display:grid;grid-template-columns:48px repeat(7,1fr)}.cal-hcell{padding:8px 4px;text-align:center;border-bottom:1px solid var(--border);border-right:1px solid var(--border);font-size:.63rem;font-weight:700;text-transform:uppercase;color:var(--dim)}.cal-hcell:last-child{border-right:none}.cal-trow{display:grid;grid-template-columns:48px repeat(7,1fr)}.cal-tcell{padding:0 4px;font-size:.58rem;color:var(--dim);text-align:right;border-bottom:1px solid rgba(255,255,255,.02);border-right:1px solid var(--border);height:43px;display:flex;align-items:center;justify-content:flex-end}.cal-tcell:last-child{border-right:none}.cal-dcell{position:relative;border-bottom:1px solid rgba(255,255,255,.02);border-right:1px solid var(--border);height:43px}.cal-dcell:last-child{border-right:none}.cal-ev{position:absolute;left:2px;right:2px;top:2px;border-radius:3px;padding:1px 3px;font-size:.53rem;font-weight:600;overflow:hidden;cursor:pointer;line-height:1.2}.ev-dl{background:rgba(239,68,68,.22);color:#fca5a5;border:1px solid rgba(239,68,68,.3)}.ev-ro{background:rgba(16,185,129,.16);color:#6ee7b7;border:1px solid rgba(16,185,129,.3)}.ev-wk{background:rgba(59,130,246,.16);color:#93c5fd;border:1px solid rgba(59,130,246,.3)}.ev-tr{background:rgba(245,158,11,.16);color:#fcd34d;border:1px solid rgba(245,158,11,.3)}.ev-cr{background:rgba(139,92,246,.16);color:#c4b5fd;border:1px solid rgba(139,92,246,.3)}
.ofc-stats{display:flex;gap:10px;padding:12px 14px;background:var(--glass);border:1px solid var(--border);border-radius:12px;margin-bottom:16px;flex-wrap:wrap}.os{text-align:center;flex:1;min-width:70px}.os-n{font-size:1.3rem;font-weight:800}.os-l{font-size:.61rem;text-transform:uppercase;color:var(--dim);letter-spacing:.04em}.ofl{font-size:.64rem;text-transform:uppercase;font-weight:700;color:var(--dim);margin-bottom:10px;margin-top:14px;letter-spacing:.04em}.ofc-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:12px}.desk{padding:12px 14px;background:var(--glass);border:1px solid var(--border);border-radius:12px;transition:all .2s}.desk:hover{transform:translateY(-2px);border-color:var(--cyan)}.desk-top{display:flex;gap:8px;margin-bottom:8px;align-items:flex-start}.desk-av{width:38px;height:38px;border-radius:9px;background:linear-gradient(135deg,var(--purple),var(--cyan));display:flex;align-items:center;justify-content:center;font-size:1rem;flex-shrink:0;border:1px solid var(--border);position:relative}.desk-ind{position:absolute;bottom:-1px;right:-1px;width:9px;height:9px;border-radius:50%;border:1.5px solid var(--bg)}.di-on{background:var(--emerald);animation:pulse 2s infinite}.di-sb{background:var(--amber)}.di-off{background:var(--dim)}.desk-name{font-size:.8rem;font-weight:700;color:#fff}.desk-role{font-size:.64rem;color:var(--dim)}.desk-task{font-size:.71rem;color:var(--dim);margin:5px 0;line-height:1.4}.desk-tags{display:flex;gap:3px;flex-wrap:wrap}.desk-tag{font-size:.59rem;background:rgba(255,255,255,.06);padding:1px 5px;border-radius:999px;color:var(--dim)}
.team-sec{margin-bottom:28px}.team-lbl{font-size:.64rem;font-weight:700;text-transform:uppercase;color:var(--dim);margin-bottom:12px;padding-bottom:8px;border-bottom:1px solid var(--border);letter-spacing:.04em}.team-cards{display:grid;gap:12px}.tc-1{grid-template-columns:1fr;max-width:400px;margin:0 auto}.tc-2{grid-template-columns:repeat(auto-fit,minmax(280px,1fr));max-width:660px;margin:0 auto}.tc-3{grid-template-columns:repeat(auto-fit,minmax(250px,1fr))}.tc-4{grid-template-columns:repeat(auto-fit,minmax(220px,1fr))}.tcard-team{padding:14px;background:var(--glass);border:1px solid var(--border);border-radius:12px;transition:all .2s}.tcard-team:hover{transform:translateY(-2px);border-color:var(--cyan)}.tcard-team-top{display:flex;gap:9px;margin-bottom:7px}.tcard-team-av{width:38px;height:38px;border-radius:9px;background:rgba(255,255,255,.08);display:flex;align-items:center;justify-content:center;font-size:1rem;border:1px solid var(--border);flex-shrink:0}.tcard-team-name{font-size:.87rem;font-weight:700;color:#fff}.tcard-team-role{font-size:.67rem;color:var(--dim);margin-top:1px}.tcard-team-desc{font-size:.73rem;color:var(--dim);line-height:1.5;margin:7px 0}.tcard-team-tags{display:flex;gap:4px;flex-wrap:wrap}.tcard-team-tag{font-size:.59rem;background:rgba(255,255,255,.06);padding:2px 5px;border-radius:999px;color:var(--dim)}
.team-stats{display:flex;justify-content:center;gap:20px;padding:16px;background:var(--glass);border:1px solid var(--border);border-radius:12px;margin-top:22px;flex-wrap:wrap}.team-st{text-align:center}.team-st-n{font-size:1.5rem;font-weight:800;background:linear-gradient(135deg,var(--cyan),var(--purple));-webkit-background-clip:text;-webkit-text-fill-color:transparent}.team-st-l{font-size:.62rem;text-transform:uppercase;color:var(--dim);margin-top:2px;letter-spacing:.04em}
.modal-ov{position:fixed;inset:0;z-index:1000;background:rgba(0,0,0,.76);backdrop-filter:blur(6px);display:none;align-items:center;justify-content:center;padding:16px}.modal-ov.open{display:flex;animation:fade .2s ease}.modal{background:#0f1219;border:1px solid var(--border);border-radius:12px;padding:20px;width:100%;max-width:460px;box-shadow:0 20px 60px rgba(0,0,0,.8)}.modal h3{font-size:.93rem;font-weight:700;margin-bottom:12px;color:#fff}.modal label{display:block;font-size:.71rem;color:var(--dim);margin-bottom:3px;font-weight:500}.modal input,.modal textarea,.modal select{width:100%;background:var(--glass);border:1px solid var(--border);border-radius:8px;padding:7px 10px;color:var(--text);font-size:.79rem;margin-bottom:10px;outline:none;transition:border-color .2s}.modal input:focus,.modal textarea:focus,.modal select:focus{border-color:var(--cyan)}.modal select option{background:#0f1219;color:var(--text)}.modal textarea{min-height:55px;resize:vertical}.modal-acts{display:flex;justify-content:flex-end;gap:7px;margin-top:2px}.btn-cancel{background:var(--glass);border:1px solid var(--border);color:var(--text);padding:6px 12px;border-radius:8px;font-size:.76rem;cursor:pointer;transition:all .2s}.btn-cancel:hover{border-color:var(--cyan)}
::-webkit-scrollbar{width:4px}::-webkit-scrollbar-track{background:transparent}::-webkit-scrollbar-thumb{background:rgba(255,255,255,.07);border-radius:2px}::-webkit-scrollbar-thumb:hover{background:rgba(255,255,255,.14)}
@media(max-width:1200px){.dash-kpi{grid-template-columns:repeat(2,1fr)}.dash-lower{grid-template-columns:1fr}}@media(max-width:1000px){.kanban{grid-template-columns:repeat(2,1fr)}.pipeline{grid-template-columns:repeat(3,1fr)}}@media(max-width:768px){.sidebar{transform:translateX(-100%)}.sidebar.open{transform:translateX(0)}.main{margin-left:0}.page{padding:12px}.kanban{grid-template-columns:1fr}.pipeline{grid-template-columns:1fr}}
</style>
</head>
<body>
<div class="bg"></div>
<div class="app">
<aside class="sidebar" id="sidebar">
<div class="sb-brand"><div class="sb-logo">MC</div><span class="sb-title">Mission Control</span></div>
<nav class="sb-nav">
<div class="sb-sec">Navigation</div>
<div class="nav-item active" data-page="dashboard"><span class="nav-icon">🏠</span> Dashboard</div>
<div class="nav-item" data-page="tasks"><span class="nav-icon">📋</span> Tasks <span class="nav-badge" id="badge-tasks">—</span></div>
<div class="nav-item" data-page="content"><span class="nav-icon">📝</span> Content</div>
<div class="nav-item" data-page="memory"><span class="nav-icon">🧠</span> Memory</div>
<div class="nav-item" data-page="calendar"><span class="nav-icon">📅</span> Calendar</div>
<div class="sb-sec">Workspace</div>
<div class="nav-item" data-page="office"><span class="nav-icon">🏢</span> Office</div>
<div class="nav-item" data-page="team"><span class="nav-icon">👥</span> Team</div>
</nav>
<div class="sb-footer"><div class="sb-user"><div class="sb-av">👨‍💻</div><div><div class="sb-uname">Leon</div><div class="sb-status">Online</div></div></div></div>
</aside>
<main class="main">
<header class="header">
<span class="hdr-page">Mission Control / <span id="page-title">Dashboard</span></span>
<div class="hdr-sp"></div>
<span class="hdr-clock" id="clock">--:--:--</span>
</header>
<div class="pages">

<!-- PAGE: DASHBOARD -->
<section class="page active" id="page-dashboard">
<div class="dash-kpi">
<div class="gc kpi kpi-c"><span class="kpi-icon">📋</span><div class="kpi-val" id="kpi-tasks">—</div><div class="kpi-label">Offene Tasks</div><div class="kpi-bar"></div></div>
<div class="gc kpi kpi-e"><span class="kpi-icon">🤖</span><div class="kpi-val">4</div><div class="kpi-label">Aktive Agents</div><div class="kpi-bar"></div></div>
<div class="gc kpi kpi-a"><span class="kpi-icon">🎤</span><div class="kpi-val" id="kpi-days">—</div><div class="kpi-label">Tage bis Demo</div><div class="kpi-bar"></div></div>
<div class="gc kpi kpi-p"><span class="kpi-icon">🚀</span><div class="kpi-val">3</div><div class="kpi-label">Aktive Projekte</div><div class="kpi-bar"></div></div>
</div>
<div class="dash-lower">
<div class="gc activity"><div class="sec-title">⚡ Activity <span class="sub">Live</span></div>
<div class="act-item"><div class="act-dot" style="background:var(--cyan)"></div><div><div class="act-txt"><strong>Dev</strong> — Guesty API Webhook implementiert</div><div class="act-time">1h · HostPro</div></div></div>
<div class="act-item"><div class="act-dot" style="background:var(--emerald)"></div><div><div class="act-txt"><strong>Pipeline</strong> — n8n Workflow getestet</div><div class="act-time">3h · HostPro</div></div></div>
<div class="act-item"><div class="act-dot" style="background:var(--purple)"></div><div><div class="act-txt"><strong>Leon</strong> — Supabase Schema deployed</div><div class="act-time">gestern · Infra</div></div></div>
<div class="act-item"><div class="act-dot" style="background:var(--amber)"></div><div><div class="act-txt"><strong>Pixel</strong> — v0 Mockup